using Microsoft.AspNetCore.Builder;
using PollBall;
using PollBall.Services;

var builder = WebApplication.CreateBuilder(args);

builder.Services.AddSingleton<IPollResultsService, PollResultsService>();

var env = builder.Environment;
var app = builder.Build();

app.UseMiddleware<TestMiddleware>();

app.UseStaticFiles();

app.Run(async (context) => {
    await context.Response.WriteAsync($"This text was generated by the app." +
        $"Run middleware. wwwroot folder path: {env.WebRootPath}");
});

await app.RunAsync();